# -*- coding: utf-8 -*-
"""4. Linear Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19bpiHwUBv4e9cqqSvA-3Q8YErijIAE3h
"""

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split as tts
from sklearn.metrics import r2_score
import plotly.express as px
import pandas as pd
import numpy as np

df = pd.read_csv('Salary_Data.csv')

df.head()

df.info()

fig = px.scatter(
    df, x='YearsExperience', y='Salary', opacity=0.65,
    trendline='ols', trendline_color_override='darkblue'
)
fig.show()

# Divinding the dataset to test and train set
X = df.iloc[:,[0,]].values
y = df.iloc[:,1].values
X_train, X_test, y_train, y_test = tts(X,y)

# Training the Model 
model = LinearRegression()
model.fit(X_train,y_train)

y_pred = model.predict(X_test)

r2_score(y_test,y_pred)